name: UI Tests API 24
on:
  push:
    branches: [ test_workflow ]
jobs:
  ui-tests-api-24:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: run Example app and Metaapp tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew app:connectedDebugAndroidTest :metaapp:connectedDebugAndroidTest
      - name: 'Publish Example-app Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'example-app-test-report'
          path: samples/app/build/reports/androidTests/*
      - name: 'Publish Metaapp Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'metaap-test-report'
          path: samples/metaapp/build/reports/androidTests/*

